cd("C:/Users/Uzytkownik/Documents/Julia/praca/others")
using JLD2, FileIO, DataFrames, Statistics, CSV, Plotly, Plots
@load "rmse_list3.jld2"
gr()
Plots.plot(steps, rmse3)
yaxis!("RMSE")
xaxis!("wartość delty")
Plots.savefig("rmse_3.png")

@load "rmse_list4.jld2"
gr()
Plots.plot(steps, rmse_list)
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_4.png")

@load "rmse_list5.jld2"
steps = [10, 50, 100]
gr()
Plots.plot(steps, rmse_list[1])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_1.png")
gr()
Plots.plot(steps, rmse_list[2])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_2.png")
gr()
Plots.plot(steps, rmse_list[3])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_3.png")
gr()
Plots.plot(steps, rmse_list[4])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_4.png")
gr()
Plots.plot(steps, rmse_list[5])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_5.png")
gr()
Plots.plot(steps, rmse_list[6])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_6.png")

@load "rmse_list5_new.jld2"
steps = [10, 50, 100, 200, 300, 500, 700]
gr()
Plots.plot(steps, rmse_list[4])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_2_4.png")
gr()
Plots.plot(steps, rmse_list[5])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_2_5.png")
gr()
Plots.plot(steps, rmse_list[6])
yaxis!("RMSE")
xaxis!("wartość k")
Plots.savefig("rmse_5_2_6.png")
